--! Previous: -
--! Hash: sha1:42895a6d47b4f0fc8be14ab652515af3f31fa179

-- Enter migration here
DROP TABLE IF EXISTS SWINES CASCADE;
DROP TABLE IF EXISTS TG_CHATS CASCADE;
DROP TABLE IF EXISTS TG_USERS CASCADE;

CREATE TABLE IF NOT EXISTS TG_USERS(
    id INT PRIMARY KEY NOT NULL,
    is_bot BOOLEAN NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    username TEXT
);

CREATE TABLE IF NOT EXISTS TG_CHATS(
    id INT PRIMARY KEY NOT NULL,
    chat_type TEXT NOT NULL,
    title TEXT,
    first_name TEXT,
    last_name TEXT
);

CREATE TABLE IF NOT EXISTS SWINES(
    id SERIAL NOT NULL,
    owner_id INT NOT NULL,
    chat_id INT NOT NULL,
    name TEXT NOT NULL DEFAULT 'Swine',
    weight INT NOT NULL DEFAULT 5,
    last_time_fed TIMESTAMP WITH TIME ZONE NOT NULL
        DEFAULT CURRENT_TIMESTAMP - INTERVAL '1 DAY',
    CONSTRAINT fk_chat_id_tg_chat_id 
        FOREIGN KEY(chat_id) REFERENCES TG_CHATS(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_owner_id_tg_user_id
     FOREIGN KEY(owner_id) REFERENCES TG_USERS(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
    PRIMARY KEY(owner_id, chat_id)
);

ALTER TABLE swines
DROP CONSTRAINT fk_owner_id_tg_user_id,
DROP CONSTRAINT fk_chat_id_tg_chat_id;

ALTER TABLE tg_chats ALTER COLUMN id TYPE TEXT;
ALTER TABLE tg_users ALTER COLUMN id TYPE TEXT;

ALTER TABLE swines
ALTER COLUMN owner_id TYPE TEXT,
ALTER COLUMN chat_id TYPE TEXT,
ADD  CONSTRAINT fk_chat_id_tg_chat_id 
        FOREIGN KEY(chat_id) REFERENCES TG_CHATS(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
ADD  CONSTRAINT fk_owner_id_tg_user_id
     FOREIGN KEY(owner_id) REFERENCES TG_USERS(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE;
