env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: 
  - eslint:recommended
  - google
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
plugins:
  - "@typescript-eslint"
rules:
  require-jsdoc: 0
  new-cap:
    - 0
    - capIsNewExceptions:
        - ForeignKey
        - HasMany
        - Length
        - Default
        - HasOne
        - Column
  @typescript-eslint/await-thenable: 2
  @typescript-eslint/no-floating-promises: 2
overrides:
  - files:
    - *.ts
    - *.tsx
  - extends:
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/recommended-requiring-type-checking
  - parserOptions: 
      project:
        - ./tsconfig.json