env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
plugins:
  - "@typescript-eslint"
rules:
  require-jsdoc: 0
  new-cap:
    - 2
    - capIsNewExceptions:
        - ForeignKey
        - HasMany
        - Length
        - Default
        - HasOne
        - Column
