---
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - google
overrides:
  - extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended-requiring-type-checking"
      - prettier
    files:
      - "*.ts"
      - "*.tsx"
    parserOptions:
      project:
        - ./tsconfig.json
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
plugins:
#  - unused-imports
  - "@typescript-eslint"
  - prettier
rules:
  quotes:
    - 2
    - single
    - avoid-escape
  semi:
    - 2
    - always
  "@typescript-eslint/await-thenable": 2
  "@typescript-eslint/no-floating-promises": 2
  new-cap:
    - 0
    - capIsNewExceptions:
        - ForeignKey
        - HasMany
        - Length
        - Default
        - HasOne
        - Column
  require-jsdoc: 0
  max-len:
    - 2
    - 120
    - 2
